# Generated by Django 4.1.7 on 2023-04-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_addstud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstud',
            old_name='course',
            new_name='courses',
        ),
    ]
