# Generated by Django 4.1.7 on 2023-04-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0003_rename_course_addstud_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstud',
            old_name='courses',
            new_name='course',
        ),
    ]
